export const FIELD_LABELS = {
  language: 'Language',
  category: 'Product type',
  activityType: 'Activity type',
  activitiesIncluded: 'Activities included',
  transportModes: 'Transport modes',
  transportServices: 'Transport services',
  cutoffMinutes: 'Cut-off time',
  lastMinuteBookings: 'Last-minute bookings',
  perSlotCutoff: 'Per-slot cut-off',
  visitType: 'Visit type',
  difficulty: 'Difficulty level',
  duration: 'Duration',
  durationUnit: 'Duration unit',
  title: 'Title',
  referenceCode: 'Reference code',
  shortDescription: 'Short description',
  fullDescription: 'Full description',
  highlights: 'Highlights',
  locations: 'Location',
  keywords: 'Keywords',
  whatsIncluded: "What's included",
  whatsNotIncluded: "What's not included",
  activitiesIncluded: 'Activities included',
  pickupTransportTypes: 'Pickup transport types',
  foodProvided: 'Food provided',
  meals: 'Meals',
  drinksIncluded: 'Drinks included',
  showDietaryRestrictions: 'Dietary restrictions',
  dietaryOptions: 'Dietary options',
  transportationProvided: 'Transportation provided',
  transportationType: 'Transportation type',
  guideType: 'Guide type',
  guideMaterials: 'Guide materials',
  photos: 'Photos',
  copyrightConfirmed: 'Copyright confirmation',
  notSuitableFor: 'Not suitable for',
  notAllowed: 'Not allowed',
  petFriendly: 'Pet friendly',
  mandatoryItems: 'Mandatory items',
  knowBeforeYouGo: 'Know before you go',
  emergencyCountryCode: 'Emergency country code',
  emergencyPhone: 'Emergency phone',
  voucherInfo: 'Voucher info',
  options: 'Options',
  meetingMode: 'Meeting mode',
  meetingPoint: 'Meeting point',
  meetingPointPicture: 'Meeting point picture',
  meetingPointDescription: 'Meeting point description',
  arrivalTimeType: 'Arrival time type',
  arrivalTimeCustom: 'Arrival time',
  pickupType: 'Pickup type',
  pickupDescription: 'Pickup description',
  pickupTiming: 'Pickup timing',
  pickupFinalLocationTiming: 'Pickup final location timing',
  referenceStartTime: 'Reference start time',
  pickupAreas: 'Pickup areas',
  pickupLocations: 'Pickup locations',
  pickupGeoshape: 'Pickup geoshape',
  dropoffOption: 'Dropoff option',
  dropoffLocation: 'Dropoff location',
  dropoffDescription: 'Dropoff description',
  pricingModel: 'Pricing model',
  currency: 'Currency',
  scheduleType: 'Schedule type',
  scheduleName: 'Schedule name',
  scheduleStartDate: 'Start date',
  scheduleHasEndDate: 'End date',
  scheduleEndDate: 'End date',
  timeSlots: 'Time slots',
  operatingHoursStart: 'Operating hours start',
  operatingHoursEnd: 'Operating hours end',
  dateExceptions: 'Date exceptions',
  pricingApproach: 'Pricing approach',
  uniformPrice: 'Uniform price',
  pricingCategories: 'Pricing categories',
  minParticipants: 'Min participants',
  maxParticipants: 'Max participants',
  pricingTiers: 'Pricing tiers',
  groupSizes: 'Group sizes',
  additionalPersonsEnabled: 'Additional persons',
  additionalPersonPrice: 'Additional person price',
  maxGroupsPerTimeSlot: 'Max groups per time slot',
  itinerary: 'Itinerary',
}

const FIELD_STEP_MAP = {
  language: 1,
  category: 2,
  activityType: 2,
  activitiesIncluded: 2,
  transportModes: 2,
  transportServices: 2,
  cutoffMinutes: 15,
  lastMinuteBookings: 15,
  perSlotCutoff: 15,
  visitType: 16,
  difficulty: 2,
  duration: 2,
  durationUnit: 2,
  title: 3,
  referenceCode: 3,
  shortDescription: 4,
  fullDescription: 4,
  highlights: 4,
  locations: 5,
  keywords: 6,
  whatsIncluded: 7,
  whatsNotIncluded: 7,
  activitiesIncluded: 7,
  pickupTransportTypes: 7,
  foodProvided: 7,
  meals: 7,
  drinksIncluded: 7,
  showDietaryRestrictions: 7,
  dietaryOptions: 7,
  transportationProvided: 7,
  transportationType: 7,
  guideType: 8,
  guideMaterials: 8,
  photos: 9,
  copyrightConfirmed: 9,
  notSuitableFor: 10,
  notAllowed: 10,
  petFriendly: 10,
  mandatoryItems: 10,
  knowBeforeYouGo: 10,
  emergencyCountryCode: 10,
  emergencyPhone: 10,
  voucherInfo: 10,
  options: 11,
  meetingMode: 12,
  meetingPoint: 12,
  meetingPointPicture: 12,
  meetingPointDescription: 12,
  arrivalTimeType: 12,
  arrivalTimeCustom: 12,
  pickupType: 12,
  pickupDescription: 12,
  pickupTiming: 12,
  pickupFinalLocationTiming: 12,
  referenceStartTime: 12,
  pickupAreas: 12,
  pickupLocations: 12,
  pickupGeoshape: 12,
  dropoffOption: 12,
  dropoffLocation: 12,
  dropoffDescription: 12,
  pricingModel: 13,
  currency: 13,
  scheduleType: 13,
  scheduleName: 13,
  scheduleStartDate: 13,
  scheduleEndDate: 13,
  timeSlots: 13,
  pricingApproach: 13,
  uniformPrice: 13,
  pricingCategories: 13,
  minParticipants: 13,
  maxParticipants: 13,
  pricingTiers: 13,
  groupSizes: 13,
  additionalPersonsEnabled: 13,
  additionalPersonPrice: 13,
  maxGroupsPerTimeSlot: 13,
  itinerary: 14,
}

export function getStepForField(fieldKey) {
  const baseKey = fieldKey.split('.')[0]
  return FIELD_STEP_MAP[baseKey] || null
}

export function getFieldLabel(fieldKey) {
  const exactLabel = FIELD_LABELS[fieldKey]
  if (exactLabel) return exactLabel

  const parts = fieldKey.split('.').filter(p => !/^\d+$/.test(p))

  if (parts.length >= 2) {
    const joinedKey = parts.join('.')
    const joinedLabel = FIELD_LABELS[joinedKey]
    if (joinedLabel) return joinedLabel
    const baseLabel = FIELD_LABELS[parts[0]] || parts[0]
    const fieldLabel = FIELD_LABELS[parts[1]] || parts[1]
    return `${baseLabel} — ${fieldLabel}`
  }

  return FIELD_LABELS[parts[0]] || parts[0] || fieldKey
}

export function scrollToField(fieldKey) {
  const el =
    document.querySelector(`[data-field="${CSS.escape(fieldKey)}"]`) ||
    document.getElementById(`field-${CSS.escape(fieldKey)}`)
  if (el) {
    el.scrollIntoView({ behavior: 'smooth', block: 'center' })
    if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement) {
      el.focus({ preventScroll: true })
    }
  }
}

const SECTION_LABELS = {
  language: 'Language',
  category: 'Category',
  activityType: 'Activity type',
  activitiesIncluded: 'Activities',
  transportModes: 'Transport modes',
  transportServices: 'Transport services',
  cutoffMinutes: 'Cut-off',
  lastMinuteBookings: 'Last-minute bookings',
  perSlotCutoff: 'Per-slot cut-off',
  visitType: 'Visit type',
  difficulty: 'Difficulty',
  duration: 'Duration',
  title: 'Title',
  shortDescription: 'Descriptions & highlights',
  fullDescription: 'Descriptions & highlights',
  highlights: 'Descriptions & highlights',
  locations: 'Location',
  keywords: 'Keywords',
  whatsIncluded: 'Inclusions',
  whatsNotIncluded: 'Inclusions',
  activitiesIncluded: 'Inclusions',
  pickupTransportTypes: 'Inclusions',
  foodProvided: 'Inclusions',
  meals: 'Inclusions',
  drinksIncluded: 'Inclusions',
  dietaryOptions: 'Inclusions',
  transportationProvided: 'Inclusions',
  transportationType: 'Inclusions',
  guideType: 'Guide information',
  guideMaterials: 'Guide information',
  photos: 'Photos',
  copyrightConfirmed: 'Photos',
  notSuitableFor: 'Extra information',
  notAllowed: 'Extra information',
  petFriendly: 'Extra information',
  mandatoryItems: 'Extra information',
  knowBeforeYouGo: 'Extra information',
  emergencyCountryCode: 'Extra information',
  emergencyPhone: 'Extra information',
  voucherInfo: 'Extra information',
  options: 'Options',
  meetingMode: 'Meeting point or pickup',
  meetingPoint: 'Meeting point or pickup',
  meetingPointPicture: 'Meeting point or pickup',
  meetingPointDescription: 'Meeting point or pickup',
  arrivalTimeType: 'Meeting point or pickup',
  pickupType: 'Meeting point or pickup',
  pickupDescription: 'Meeting point or pickup',
  pickupTiming: 'Meeting point or pickup',
  pickupAreas: 'Meeting point or pickup',
  pickupLocations: 'Meeting point or pickup',
  dropoffOption: 'Meeting point or pickup',
  dropoffLocation: 'Meeting point or pickup',
  pricingModel: 'Availability & Pricing',
  currency: 'Availability & Pricing',
  scheduleType: 'Availability & Pricing',
  scheduleName: 'Availability & Pricing',
  scheduleStartDate: 'Availability & Pricing',
  scheduleEndDate: 'Availability & Pricing',
  timeSlots: 'Availability & Pricing',
  pricingApproach: 'Availability & Pricing',
  uniformPrice: 'Availability & Pricing',
  pricingCategories: 'Availability & Pricing',
  minParticipants: 'Availability & Pricing',
  maxParticipants: 'Availability & Pricing',
  pricingTiers: 'Availability & Pricing',
  itinerary: 'Itinerary',
}

export function getSectionLabel(fieldKey) {
  const baseKey = fieldKey.split('.')[0]
  return SECTION_LABELS[baseKey] || FIELD_LABELS[baseKey] || baseKey
}
